<?php

// This file acts as a dynamic "Controller" entrypoint (courier-style console/cron)

require_once __DIR__ . '/../classes/TravelGlobal.php';

$global = \TravelApp\Classes\TravelGlobal::getInstance();
$db = $global->getDb();

// 1. Dynamic inclusion (the AST cannot know which file gets included until runtime)
$providerName = $_REQUEST['provider'] ?? $argv[1] ?? 'unknown';
$scraperFile = __DIR__ . "/../scrapers/" . $providerName . "_common.php";

if (file_exists($scraperFile)) {
    // 2. Implicitly declared variables and scope leakage
    // The included file expects `$db`, `$global`, `$tripId` to exist!
    require_once $scraperFile;
}
else {
    die("Provider not found");
}

// ANTI-PATTERN: direct access to the `orders` table owned by order-service (TypeScript)
// Instead of calling the order-service REST API, we read straight from the shared DB.
// This is the cross-language coupling (PHP <-> TS) that CodeRadius must detect.
$tripId = (int)($argv[1] ?? $_REQUEST['ID_TRIP'] ?? 0);
$existingOrders = $db->query("SELECT id, customer_id, status FROM orders WHERE customer_id = (SELECT user_id FROM trips WHERE id = $tripId)")->fetch_all();

// ANTI-PATTERN: direct access to the `users` table shared with order-service AND notification-service
// Three different services (TS, PHP Symfony, PHP legacy) read the same table.
$userData = $db->query("SELECT name, email FROM users WHERE id = " . ($existingOrders[0]['customer_id'] ?? 0))->fetch_assoc();

// 3. State extraction from an opaque binary blob
// Simulates reading session_cache / suppliers_json
$rawBlob = $db->query("SELECT UNCOMPRESS(api_response_blob) as payload FROM api_logs WHERE req_id = '123'")->fetch_assoc();

if ($rawBlob) {
    // The parser sees "unserialize" but has NO idea of the object/array structure
    $responseData = unserialize(base64_decode($rawBlob['payload']));

    // 4. Variable variables ($$var) and extract()
    // Exposes all the array keys as local variables ($status, $price, $passengers...)
    extract($responseData);


    // "Pass-through" publishing
    // We send the entire decoded array to PubSub. The PubSub topic schema
    // at this point it is a complete mystery for static analysis.
    $publisher = new \TravelApp\Events\PubSubPublisher(new \TravelApp\Events\PubSubClient(), 'trips-topic', new \TravelApp\Events\LoggerInterface());

    // Instead of using a typed DTO (SuccessfulBooking), we pass a dynamically built stdClass object
    $dynamicMessage = (object)[
        'event_name' => 'API_RAW_RESPONSE_PASSTHROUGH',
        'raw_payload' => $responseData, // Unknown schema
        'extracted_price' => $price ?? 0 // Variable generated by extract()!
    ];

    // The publisher's publish() method would expect a Message DTO, but in legacy PHP
    // type hints are missing and the object gets brutally serialized to JSON.
    $publisher->publish($dynamicMessage);
}
