/**
 * Build script: Bundles the React dashboard UI into a single self-contained HTML file,
 * then wraps it as a TypeScript module for the CLI.
 *
 * Uses Bun's native bundler — no Vite, no esbuild, no plugins.
 *
 * Usage: bun run scripts/build-dashboard.ts
 */

import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const UI_DIR = path.join(ROOT, 'packages/dashboard-ui');
const ENTRY = path.join(UI_DIR, 'src/main.tsx');
const OUTPUT_FILE = path.join(ROOT, 'src/cli/commands/ui/template-react.ts');

async function build() {
    const startMs = performance.now();

    // ── Step 1: Bundle JS ────────────────────────────────────────────────────
    const result = await Bun.build({
        entrypoints: [ENTRY],
        target: 'browser',
        format: 'esm',
        minify: true,
        tsconfig: path.join(UI_DIR, 'tsconfig.json'),
        define: {
            'process.env.NODE_ENV': '"production"',
        },
    });

    if (!result.success) {
        console.error('  Build failed:');
        for (const log of result.logs) {
            console.error('    ', log);
        }
        process.exit(1);
    }

    let jsCode = '';
    let cssCode = '';

    for (const output of result.outputs) {
        if (output.kind === 'entry-point' || output.kind === 'chunk') {
            jsCode += await output.text();
        }
    }

    // ── Step 2: Bundle CSS separately ────────────────────────────────────────
    const cssResult = await Bun.build({
        entrypoints: [path.join(UI_DIR, 'src/styles/index.css')],
        target: 'browser',
        minify: true,
    });

    if (cssResult.success) {
        for (const output of cssResult.outputs) {
            cssCode += await output.text();
        }
    }

    for (const output of result.outputs) {
        if (output.path.endsWith('.css')) {
            cssCode += await output.text();
        }
    }

    // ── Step 3: Construct single-file HTML ───────────────────────────────────
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dashboard — CodeRadius</title>
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%23fdfdf5'%3E%3Cmask id='v2'%3E%3Crect width='24' height='24' fill='white'/%3E%3Cline x1='12' y1='12' x2='22' y2='4' stroke='black' stroke-width='2.5' stroke-linecap='round'/%3E%3Ccircle cx='12' cy='12' r='2' fill='black'/%3E%3C/mask%3E%3Ccircle cx='12' cy='12' r='10' mask='url(%23v2)'/%3E%3C/svg%3E">
  <style>${cssCode}</style>
</head>
<body>
  <div id="root"></div>
  <script>
    // Data injection: CLI replaces this placeholder
    window.__RADIUS_DATA__ = __REPORT_DATA__;
  </script>
  <script type="module">${jsCode.replace(/<\/script>/gi, '<\\/script>')}</script>
</body>
</html>`;

    // ── Step 4: Wrap as TypeScript module ────────────────────────────────────
    const tsModule = `// AUTO-GENERATED by scripts/build-dashboard.ts — do not edit directly.\n// Bundled with Bun ${Bun.version}\nexport default ${JSON.stringify(html)};\n`;
    await Bun.write(OUTPUT_FILE, tsModule);

    const elapsed = (performance.now() - startMs).toFixed(0);
    const sizeKB = (html.length / 1024).toFixed(1);
    const jsSizeKB = (jsCode.length / 1024).toFixed(1);
    const cssSizeKB = (cssCode.length / 1024).toFixed(1);

    console.log(`  Dashboard built with Bun (${elapsed}ms)`);
    console.log(`     JS: ${jsSizeKB} KB | CSS: ${cssSizeKB} KB | Total HTML: ${sizeKB} KB`);
}

build().catch(err => {
    console.error('  Build failed:', err.message);
    process.exit(1);
});
