/**
 * embed-fonts.ts — Download Google Fonts as woff2, base64-encode, and generate fonts.css
 *
 * Fetches Inter (400-700) and JetBrains Mono (400-700) latin-subset woff2 files,
 * encodes them as base64 data URIs, and writes a self-contained fonts.css.
 *
 * Both are variable fonts: a single woff2 file covers all weights per family.
 *
 * Usage: bun run scripts/embed-fonts.ts
 *
 * The output (src/report/styles/fonts.css) should be committed to the repo.
 * After running, re-run `bun run scripts/build-report.ts` to update the template.
 */

import { writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUTPUT = path.join(ROOT, 'src/report/styles/fonts.css');

interface FontFamily {
    family: string;
    weights: number[];
    /** Direct URL to the latin-subset woff2 file from Google Fonts CDN */
    url: string;
}

// Latin-subset woff2 URLs from Google Fonts CSS API (v20 Inter, v24 JetBrains Mono).
// Both fonts use a single variable woff2 file for all weights.
const FONT_FAMILIES: FontFamily[] = [
    {
        family: 'Inter',
        weights: [400, 500, 600, 700],
        url: 'https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7W0Q5nw.woff2',
    },
    {
        family: 'JetBrains Mono',
        weights: [400, 500, 600, 700],
        url: 'https://fonts.gstatic.com/s/jetbrainsmono/v24/tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPxDcwgknk-4.woff2',
    },
];

const LATIN_UNICODE_RANGE = 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

async function downloadAsBase64(url: string): Promise<string> {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    return buf.toString('base64');
}

async function main() {
    console.log('⏳ Downloading and encoding fonts...\n');

    const blocks: string[] = [
        '/* AUTO-GENERATED by scripts/embed-fonts.ts — do not edit directly. */',
        '/* Fonts: Inter 400-700, JetBrains Mono 400-700 (woff2, base64-embedded, latin subset) */',
        '',
    ];

    for (const font of FONT_FAMILIES) {
        process.stdout.write(`  📥 ${font.family}...`);

        const b64 = await downloadAsBase64(font.url);
        const sizeKB = (b64.length * 0.75 / 1024).toFixed(1);

        // Emit one @font-face per weight, all pointing to the same data URI.
        // Browsers will only download the data once since it's inline.
        for (const weight of font.weights) {
            blocks.push(`@font-face {`);
            blocks.push(`    font-family: '${font.family}';`);
            blocks.push(`    font-style: normal;`);
            blocks.push(`    font-weight: ${weight};`);
            blocks.push(`    font-display: swap;`);
            blocks.push(`    src: url(data:font/woff2;base64,${b64}) format('woff2');`);
            blocks.push(`    unicode-range: ${LATIN_UNICODE_RANGE};`);
            blocks.push(`}`);
            blocks.push('');
        }

        console.log(` ok (${sizeKB} KB, ${font.weights.length} weights)`);
    }

    const css = blocks.join('\n');
    writeFileSync(OUTPUT, css, 'utf8');

    const totalKB = (css.length / 1024).toFixed(1);
    console.log(`\nWrote ${OUTPUT} (${totalKB} KB)`);
    console.log('   Run `bun run scripts/build-report.ts` to rebuild the template.');
}

main().catch(err => {
    console.error('Failed:', err);
    process.exit(1);
});
