#!/usr/bin/env bun
/**
 * scripts/generate-embedded-packs.ts — Embed built-in policy packs as code.
 *
 * The compiled binary (bun build --compile) cannot read the pack YAML files
 * from disk at runtime: import.meta.dir points into the $bunfs virtual
 * filesystem and runtime fs reads are not embedded. This script snapshots
 * `src/policy-runner/packs/<pack>/*.yaml` into a plain TypeScript module so
 * the packs travel inside the bundle.
 *
 * Run manually after editing a pack, or rely on the release build which
 * regenerates before compiling. The drift-guard unit test
 * (tests/unit/ingestion/policy-packs-embedded.test.ts) fails when the
 * committed snapshot is stale.
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.join(import.meta.dirname, '..');
const PACKS_DIR = path.join(ROOT, 'src', 'policy-runner', 'packs');
const OUT_FILE = path.join(ROOT, 'src', 'policy-runner', 'packs.generated.ts');

export type EmbeddedPacksMap = Record<string, Record<string, string>>;

/** Snapshot every `<pack>/*.{yaml,yml}` under `packsDir` into a nested map. */
export function buildEmbeddedPacksMap(packsDir: string): EmbeddedPacksMap {
    const map: EmbeddedPacksMap = {};
    const packs = readdirSync(packsDir, { withFileTypes: true })
        .filter(e => e.isDirectory())
        .map(e => e.name)
        .sort();

    for (const pack of packs) {
        const packDir = path.join(packsDir, pack);
        const files = readdirSync(packDir, { recursive: true, encoding: 'utf-8' })
            .filter(f => /\.ya?ml$/.test(f))
            .sort();
        if (files.length === 0) continue;

        map[pack] = {};
        for (const file of files) {
            map[pack]![file] = readFileSync(path.join(packDir, file), 'utf-8');
        }
    }
    return map;
}

export function renderEmbeddedPacksModule(map: EmbeddedPacksMap): string {
    return [
        '// AUTO-GENERATED by scripts/generate-embedded-packs.ts — do not edit.',
        '// Source of truth: src/policy-runner/packs/**/*.yaml',
        '// Regenerate with: bun run gen:packs',
        '',
        '/** Built-in policy packs snapshotted at build time so the compiled',
        ' *  binary can load them without filesystem access. Keyed by pack name,',
        ' *  then by file name relative to the pack directory. */',
        `export const EMBEDDED_PACKS: Readonly<Record<string, Record<string, string>>> = ${JSON.stringify(map, null, 4)};`,
        '',
    ].join('\n');
}

if (import.meta.main) {
    const map = buildEmbeddedPacksMap(PACKS_DIR);
    writeFileSync(OUT_FILE, renderEmbeddedPacksModule(map));
    const packCount = Object.keys(map).length;
    const fileCount = Object.values(map).reduce((n, files) => n + Object.keys(files).length, 0);
    console.log(`Embedded ${fileCount} rule file(s) across ${packCount} pack(s) → ${path.relative(ROOT, OUT_FILE)}`);
}
