#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────
# install-wt-hooks.sh — wires `wt-bootstrap.sh` into the repo's git hooks.
#
# After this runs, ANY worktree creation (manual `git worktree add`, Claude
# Code's `Agent({isolation:'worktree'})`, CI, etc.) automatically triggers
# the bootstrap because `post-checkout` fires when the new worktree's
# branch is checked out.
#
# Hooks live in the main repo's `.git/hooks/` and are SHARED across all
# worktrees, so we only need to install once.
#
# Idempotent: re-running just refreshes the hook content.
# ──────────────────────────────────────────────────────────────────────────
set -euo pipefail

common_dir="$(cd "$(git rev-parse --git-common-dir)" && pwd)"
hooks_dir="$common_dir/hooks"
hook_path="$hooks_dir/post-checkout"
main_root="$(cd "$common_dir/.." && pwd)"

mkdir -p "$hooks_dir"

# The hook is self-locating: at fire time, it looks for wt-bootstrap.sh in
# the new worktree first (works before the script is merged to main) and
# falls back to the main repo's path (works once merged). If neither
# exists, the hook silently no-ops — never blocks `git worktree add`.

cat > "$hook_path" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-wt-hooks.sh — do not edit by hand.
#
# Bootstraps a freshly-created worktree (env files + dependencies) so the
# pattern works for: manual `git worktree add`, `gwa.sh`, Claude Code's
# `Agent({isolation:'worktree'})`, and any CI flow.
#
# post-checkout args: $1=oldHEAD $2=newHEAD $3=branchCheckout(1)|fileCheckout(0)
set -e

[ "$3" = "1" ] || exit 0

# Heuristic: "fresh worktree" iff neither .env nor node_modules exists yet.
# A routine `git checkout other-branch` in an established worktree has at
# least one of these and is therefore skipped.
if [ -e .env ] || [ -e node_modules ]; then
    exit 0
fi

# Skip the main repo itself — bootstrap is for worktrees only.
common_dir="$(git rev-parse --git-common-dir 2>/dev/null)" || exit 0
[ -z "$common_dir" ] && exit 0
main_root="$(cd "$common_dir/.." 2>/dev/null && pwd)" || exit 0
[ "$main_root" = "$(pwd)" ] && exit 0

# Locate wt-bootstrap.sh:
#   1. in the new worktree itself (works on feature branches BEFORE the
#      script has been merged to main)
#   2. in the main repo (works AFTER merge to main)
# If neither exists, no-op.
for candidate in "./scripts/wt-bootstrap.sh" "$main_root/scripts/wt-bootstrap.sh"; do
    if [ -x "$candidate" ]; then
        "$candidate" "$(pwd)" || true
        exit 0
    fi
done
HOOK

chmod +x "$hook_path"

echo "[install-wt-hooks] installed: $hook_path"
echo "[install-wt-hooks] hook fires on: post-checkout (branch checkout in fresh worktree)"
echo "[install-wt-hooks] bootstrap is resolved at fire-time, looking in:"
echo "                     1) ./scripts/wt-bootstrap.sh   (the new worktree)"
echo "                     2) $main_root/scripts/wt-bootstrap.sh   (main repo)"
