#!/usr/bin/env bun
/**
 * scripts/sync-branding.ts — Sync branding assets (logo) across the codebase.
 * Source of truth: src/cli/ui/logo.txt
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.join(import.meta.dirname, '..');
const LOGO_TXT = path.join(ROOT, 'src/cli/ui', 'logo.txt');
const INSTALL_SH = path.join(ROOT, 'scripts', 'install.sh');

if (!fs.existsSync(LOGO_TXT)) {
    console.error(`Source logo not found at ${LOGO_TXT}`);
    process.exit(1);
}

const logoLines = fs.readFileSync(LOGO_TXT, 'utf-8')
    .split('\n')
    .filter(line => line.length > 0);

// --- Sync install.sh ---
if (fs.existsSync(INSTALL_SH)) {
    let content = fs.readFileSync(INSTALL_SH, 'utf-8');
    
    const startMarker = '# ── LOGO START ──';
    const endMarker = '# ── LOGO END ──';
    
    const startIdx = content.indexOf(startMarker);
    const endIdx = content.indexOf(endMarker);
    
    if (startIdx !== -1 && endIdx !== -1) {
        const logoSection = logoLines.map((line, i) => {
            if (i === 2) return `echo -e "\${CYAN}${line}\${RESET}  \${BOLD}CODERADIUS\${RESET}"`;
            if (i === 3) return `echo -e "\${CYAN}${line}\${RESET}  CodeRadius CLI — Installer"`;
            return `echo -e "\${CYAN}${line}\${RESET}"`;
        }).join('\n');
        const newContent = content.substring(0, startIdx + startMarker.length) + 
                          '\n' + logoSection + '\n' + 
                          content.substring(endIdx);
        
        fs.writeFileSync(INSTALL_SH, newContent, 'utf-8');
        console.log('Synced logo to scripts/install.sh');
    } else {
        console.warn('Could not find logo markers in scripts/install.sh. Skipping sync.');
    }
}

// --- Sync logo-data.ts for SEA bundler ---
const LOGO_DATA_TS = path.join(ROOT, 'src', 'cli', 'ui', 'logo-data.ts');
const logoDataContent = `// AUTO-GENERATED BY sync-logo.ts — DO NOT EDIT
export const rawLogo = [
${logoLines.map(l => `    ${JSON.stringify(l)}`).join(',\n')}
];
`;
fs.writeFileSync(LOGO_DATA_TS, logoDataContent, 'utf-8');
console.log('Synced logo to src/cli/ui/logo-data.ts');

console.log('Branding sync complete.');
